name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: wobcom-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --log-format bar-with-logs -v
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: wobcom-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --log-format bar-with-logs -v .#wandaNixosTest
